name: CI
on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - run: npx docusaurus build --out-dir site
    - name: Commit to GH Pages Branch
      uses: stefanzweifel/git-auto-commit-action@v4.4.0
      with:
        commit_message: Site publish after commit to master